export const products = [
  {
    id: "1",
    name: "Cyan Hoodie",
    description: "Awesome cyan hoodie with a comfortable fit.",
    price: 19.99,
    rating: 4.5,
    category: "clothing",
    tags: ["hoodie", "cyan", "comfortable"],
    stock: 100,
    discount: 0.1,
    reviewCount: 25,
    imagePath: "/images/products/cyan_hoodie.png",
    arUrl:
      "https://lens.snap.com/experience/28e88a69-a151-4439-b08b-263a8934ffd0",
  },
  {
    id: "2",
    name: "Vintage Brown Coat",
    description: "Stylish vintage brown coat for a classic look.",
    price: 49.99,
    rating: 4.5,
    category: "clothing",
    tags: ["coat", "brown", "vintage"],
    stock: 50,
    discount: 0.15,
    reviewCount: 15,
    imagePath: "/images/products/vintage_brown_coat.jpeg",
    arUrl:
      "https://lens.snap.com/experience/d14d0a53-757a-4480-98ae-3f8ae5edb9aa",
  },
  {
    id: "3",
    name: "Yellow Dress",
    description: "Bright yellow dress perfect for summer.",
    price: 20.99,
    rating: 4.0,
    category: "clothing",
    tags: ["dress", "yellow", "summer"],
    stock: 10,
    discount: 0.12,
    reviewCount: 20,
    imagePath: "/images/products/yellow_dress.jpg",
    arUrl:
      "https://lens.snap.com/experience/6d72b6b0-8724-4d2e-814f-21fe27f05604",
  },
  {
    id: "4",
    name: "Golden Dress",
    description: "Classy golden dress perfect for prom.",
    price: 50.99,
    rating: 5.0,
    category: "clothing",
    tags: ["dress", "gold", "prom"],
    stock: 75,
    discount: 0.5,
    reviewCount: 30,
    imagePath: "/images/products/golden_dress.png",
    arUrl:
      "https://lens.snap.com/experience/324277d7-8fbe-490b-84c6-e44975fdac98",
  },
  {
    id: "5",
    name: "Black Glasses",
    description:
      "Stylish black glasses perfect for any occasion. Premium quality with modern design.",
    price: 89.99,
    rating: 4.8,
    category: "accessories",
    tags: ["glasses", "black", "stylish", "premium"],
    stock: 45,
    discount: 0.2,
    reviewCount: 42,
    imagePath: "/images/products/sunglasses.jpg",
    arUrl:
      "https://lens.snap.com/experience/de17f7aa-7695-4384-b05b-c713daa575a6",
  },
  {
    id: "6",
    name: "Yellow Track Pants",
    description:
      "Comfortable track pants for casual wear. Made with breathable fabric.",
    price: 29.99,
    rating: 4.2,
    category: "clothing",
    tags: ["pants", "track", "comfortable", "casual"],
    stock: 60,
    discount: 0.15,
    reviewCount: 18,
    imagePath: "/images/products/yellow_trackpants.png",
    arUrl:
      "https://lens.snap.com/experience/293b1d23-0362-48b6-aa2e-47eada1b9e58",
  },
  {
    id: "7",
    name: "White T-Shirt",
    description:
      "Classic white t-shirt with a comfortable fit. Perfect for everyday wear.",
    price: 15.99,
    rating: 4.3,
    category: "clothing",
    tags: ["t-shirt", "white", "comfortable"],
    stock: 120,
    discount: 0.05,
    reviewCount: 35,
    imagePath: "/images/products/white-tshirt.webp",
    arUrl:
      "https://lens.snap.com/experience/92fce070-1c6e-42b3-8ada-63f61bd72ff4",
  },
];
