export const products = [
  {
    id: '1',
    name: 'Cyan Hoodie',
    description: 'Awesome cyan hoodie with a comfortable fit.',
    price: 19.99,
    rating: 4.5,
    category: 'clothing',
    tags: ['hoodie', 'cyan', 'comfortable'],
    stock: 100,
    discount: 0.1,
    reviewCount: 25,
    imageUrl: 'https://example.com/product1.jpg',
    imagePath: '/images/products/cyan_hoodie.png',
    arUrl: 'https://lens.snap.com/experience/94eb7c74-e3e0-4040-bddb-90b9c08d4e4d',
  },
  {
    id: '2',
    name: 'Vintage Brown Coat',
    description: 'Stylish vintage brown coat for a classic look.',
    price: 49.99,
    rating: 4.5,
    category: 'clothing',
    tags: ['coat', 'brown', 'vintage'],
    stock: 50,
    discount: 0.15,
    reviewCount: 15,
    imageUrl: 'https://example.com/product2.jpg',
    imagePath: '/images/products/vintage_brown_coat.jpeg',
    arUrl: 'https://lens.snap.com/experience/d14d0a53-757a-4480-98ae-3f8ae5edb9aa',
  },
  {
    id: '3',
    name: 'Yellow Dress',
    description: 'Bright yellow dress perfect for summer.',
    price: 20.99,
    rating: 4.0,
    category: 'clothing',
    tags: ['dress', 'yellow', 'summer'],
    stock: 10,
    discount: 12,
    reviewCount: 20,
    imageUrl: 'https://example.com/product3.jpg',
    imagePath: '/images/products/yellow_dress.jpg',
    arUrl: 'https://lens.snap.com/experience/6d72b6b0-8724-4d2e-814f-21fe27f05604',
  },
  {
    id: '4',
    name: 'Golden Dress',
    description: 'Classy golden dress perfect for prom.',
    price: 50.99,
    rating: 5.0,
    category: 'clothing',
    tags: ['dress', 'gold', 'prom'],
    stock: 75,
    discount: 0.5,
    reviewCount: 30,
    imageUrl: 'https://example.com/product4.jpg',
    imagePath: '/images/products/golden_dress.png',
    arUrl: 'https://lens.snap.com/experience/324277d7-8fbe-490b-84c6-e44975fdac98',
  }
];